In [1]:
import pandas as pd
from pathlib import Path

root=Path.cwd().parent
sales=pd.read_parquet(root/"data"/"processed"/"sales.parquet")

sales.shape

(1037143, 9)

In [2]:
sales["Month"] = sales["InvoiceDate"].dt.to_period("M")
monthly = sales.groupby("Month")["Revenue"].sum()
monthly

Month
2009-12     801433.84
2010-01     622906.82
2010-02     539767.65
2010-03     764376.40
2010-04     649204.75
2010-05     645739.00
2010-06     700117.70
2010-07     634982.09
2010-08     676215.89
2010-09     871912.38
2010-10    1098145.32
2010-11    1442437.89
2010-12    1214320.13
2011-01     671992.41
2011-02     508952.87
2011-03     691485.70
2011-04     516339.79
2011-05     741275.74
2011-06     738876.88
2011-07     689397.74
2011-08     736667.22
2011-09    1030500.36
2011-10    1106719.54
2011-11    1457745.53
2011-12     615501.60
Freq: M, Name: Revenue, dtype: float64

In [3]:
sales["Year"] = sales["InvoiceDate"].dt.year
sales["MonthNum"] = sales["InvoiceDate"].dt.month

sales.groupby(["Year", "MonthNum"])["Revenue"].sum()

Year  MonthNum
2009  12           801433.84
2010  1            622906.82
      2            539767.65
      3            764376.40
      4            649204.75
      5            645739.00
      6            700117.70
      7            634982.09
      8            676215.89
      9            871912.38
      10          1098145.32
      11          1442437.89
      12          1214320.13
2011  1            671992.41
      2            508952.87
      3            691485.70
      4            516339.79
      5            741275.74
      6            738876.88
      7            689397.74
      8            736667.22
      9           1030500.36
      10          1106719.54
      11          1457745.53
      12           615501.60
Name: Revenue, dtype: float64

In [4]:
sales.groupby("Country")["Revenue"].sum().sort_values(ascending=False)

Country
United Kingdom          17288448.99
Ireland                   630552.00
Netherlands               549952.66
Germany                   388959.99
France                    317005.53
Australia                 168484.66
Spain                      98840.54
Switzerland                94270.29
Sweden                     86353.04
Denmark                    68560.19
Belgium                    57322.77
Portugal                   48937.11
Japan                      47138.39
Channel Islands            44353.76
Norway                     42362.48
Italy                      29363.42
Finland                    25243.34
Cyprus                     24614.44
Austria                    20297.01
Greece                     18711.19
Hong Kong                  13875.25
Singapore                  13158.16
Other                      12095.26
Israel                     11334.66
Poland                     10462.45
United Arab Emirates       10273.23
USA                         7920.01
Lithuania                   6553.74
Iceland                     5633.32
Malta                       4757.34
Canada                      4332.10
RSA                         3369.03
Bahrain                     3109.79
Thailand                    3070.54
Lebanon                     1905.58
Brazil                      1411.87
Bermuda                     1253.14
Korea                       1118.51
Czech Republic               786.74
West Indies                  536.41
Saudi Arabia                 145.92
Nigeria                      140.39
Name: Revenue, dtype: float64

In [5]:
sales.groupby("Description")["Revenue"].sum().sort_values(ascending=False).head(20)

Description
REGENCY CAKESTAND 3 TIER               344563.25
WHITE HANGING HEART T-LIGHT HOLDER     266923.55
PAPER CRAFT , LITTLE BIRDIE            168469.60
JUMBO BAG RED RETROSPOT                150935.56
PARTY BUNTING                          149187.05
ASSORTED COLOUR BIRD ORNAMENT          132187.92
PAPER CHAIN KIT 50'S CHRISTMAS         123141.54
CHILLI LIGHTS                           85489.91
MEDIUM CERAMIC TOP STORAGE JAR          81700.92
ROTATING SILVER ANGELS T-LIGHT HLDR     74448.92
JUMBO BAG STRAWBERRY                    69565.89
BLACK RECORD COVER FRAME                69329.47
RABBIT NIGHT LIGHT                      66964.99
HOT WATER BOTTLE TEA AND SYMPATHY       63517.75
WOOD BLACK BOARD ANT WHITE FINISH       62842.02
JUMBO STORAGE BAG SUKI                  62285.28
PAPER CHAIN KIT VINTAGE CHRISTMAS       61721.99
CHOCOLATE HOT WATER BOTTLE              60763.12
EDWARDIAN PARASOL NATURAL               60687.03
VINTAGE UNION JACK BUNTING              60668.54
Name: Revenue, dtype: float64

# Cohort Retention

In [6]:
customers = pd.read_parquet(root / "data" / "processed" / "customers.parquet")
customers["Month"] = customers["InvoiceDate"].dt.to_period("M")
first_month=customers.groupby('Customer ID')["Month"].min()
first_month

Customer ID
12346    2009-12
12347    2010-10
12348    2010-09
12349    2010-04
12350    2011-02
          ...
18283    2010-02
18284    2010-10
18285    2010-02
18286    2009-12
18287    2010-05
Name: Month, Length: 5861, dtype: period[M]

In [7]:
customers["CohortMonth"] = customers["Customer ID"].map(first_month)
customers.head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Month,CohortMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.40,2009-12,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.00,2009-12,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.00,2009-12,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.80,2009-12,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.00,2009-12,2009-12
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085,United Kingdom,39.60,2009-12,2009-12
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.00,2009-12,2009-12
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085,United Kingdom,59.50,2009-12,2009-12
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085,United Kingdom,30.60,2009-12,2009-12
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085,United Kingdom,45.00,2009-12,2009-12
10,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085,United Kingdom,39.60,2009-12,2009-12
11,489435,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2009-12-01 07:46:00,2.55,13085,United Kingdom,30.60,2009-12,2009-12
12,489436,48173C,DOOR MAT BLACK FLOCK,10,2009-12-01 09:06:00,5.95,13078,United Kingdom,59.50,2009-12,2009-12
13,489436,21755,LOVE BUILDING BLOCK WORD,18,2009-12-01 09:06:00,5.45,13078,United Kingdom,98.10,2009-12,2009-12
14,489436,21754,HOME BUILDING BLOCK WORD,3,2009-12-01 09:06:00,5.95,13078,United Kingdom,17.85,2009-12,2009-12
15,489436,84879,ASSORTED COLOUR BIRD ORNAMENT,16,2009-12-01 09:06:00,1.69,13078,United Kingdom,27.04,2009-12,2009-12
16,489436,22119,PEACE WOODEN BLOCK LETTERS,3,2009-12-01 09:06:00,6.95,13078,United Kingdom,20.85,2009-12,2009-12
17,489436,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-01 09:06:00,1.45,13078,United Kingdom,17.40,2009-12,2009-12
18,489436,22296,HEART IVORY TRELLIS LARGE,12,2009-12-01 09:06:00,1.65,13078,United Kingdom,19.80,2009-12,2009-12
19,489436,22295,HEART FILIGREE DOVE LARGE,12,2009-12-01 09:06:00,1.65,13078,United Kingdom,19.80,2009-12,2009-12

In [8]:
customers["CohortIndex"] = (customers["Month"] - customers["CohortMonth"]).apply(lambda x: x.n)
customers[["Month", "CohortMonth", "CohortIndex"]].head(20)

      Month CohortMonth  CohortIndex
0   2009-12     2009-12            0
1   2009-12     2009-12            0
2   2009-12     2009-12            0
3   2009-12     2009-12            0
4   2009-12     2009-12            0
5   2009-12     2009-12            0
6   2009-12     2009-12            0
7   2009-12     2009-12            0
8   2009-12     2009-12            0
9   2009-12     2009-12            0
10  2009-12     2009-12            0
11  2009-12     2009-12            0
12  2009-12     2009-12            0
13  2009-12     2009-12            0
14  2009-12     2009-12            0
15  2009-12     2009-12            0
16  2009-12     2009-12            0
17  2009-12     2009-12            0
18  2009-12     2009-12            0
19  2009-12     2009-12            0

In [9]:
counts = customers.groupby(["CohortMonth", "CohortIndex"])["Customer ID"].nunique()
counts

CohortMonth  CohortIndex
2009-12      0              952
             1              336
             2              317
             3              405
             4              360
                           ...
2011-10      1               70
             2               35
2011-11      0              191
             1               27
2011-12      0               28
Name: Customer ID, Length: 325, dtype: int64

In [10]:
cohort_table = counts.unstack(1)
cohort_table

CohortIndex,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
CohortMonth,,,,,,,,,,,,,,,,,,,,,
2009-12,952.0,336.0,317.0,405.0,360.0,342.0,359.0,327.0,321.0,344.0,...,288.0,250.0,288.0,270.0,246.0,242.0,298.0,289.0,386.0,187.0
2010-01,382.0,79.0,119.0,117.0,101.0,115.0,99.0,88.0,106.0,121.0,...,57.0,90.0,75.0,71.0,75.0,93.0,74.0,94.0,21.0,NaN
2010-02,375.0,88.0,85.0,110.0,92.0,74.0,72.0,108.0,96.0,104.0,...,75.0,60.0,61.0,54.0,86.0,86.0,62.0,22.0,NaN,NaN
2010-03,439.0,84.0,102.0,106.0,102.0,90.0,108.0,134.0,122.0,48.0,...,75.0,77.0,69.0,78.0,89.0,94.0,34.0,NaN,NaN,NaN
2010-04,293.0,56.0,56.0,47.0,54.0,65.0,81.0,77.0,31.0,32.0,...,46.0,41.0,44.0,53.0,66.0,17.0,NaN,NaN,NaN,NaN
2010-05,254.0,40.0,43.0,44.0,45.0,65.0,54.0,32.0,15.0,21.0,...,32.0,35.0,42.0,39.0,12.0,NaN,NaN,NaN,NaN,NaN
2010-06,267.0,47.0,50.0,55.0,62.0,76.0,34.0,24.0,22.0,30.0,...,33.0,35.0,54.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN
2010-07,185.0,29.0,34.0,55.0,54.0,26.0,21.0,27.0,27.0,21.0,...,32.0,44.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-08,162.0,32.0,47.0,53.0,27.0,19.0,16.0,21.0,22.0,21.0,...,32.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-09,239.0,55.0,56.0,31.0,21.0,25.0,33.0,23.0,31.0,31.0,...,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-10,375.0,97.0,55.0,47.0,33.0,31.0,49.0,52.0,40.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-11,326.0,57.0,31.0,31.0,25.0,29.0,42.0,33.0,28.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-12,76.0,7.0,4.0,7.0,9.0,5.0,4.0,7.0,4.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-01,72.0,12.0,16.0,14.0,16.0,11.0,11.0,9.0,8.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-02,125.0,20.0,20.0,23.0,27.0,20.0,20.0,19.0,19.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-03,179.0,32.0,39.0,36.0,40.0,27.0,37.0,36.0,43.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-04,106.0,26.0,21.0,21.0,19.0,25.0,19.0,27.0,12.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-05,111.0,26.0,27.0,18.0,24.0,23.0,29.0,13.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-06,108.0,25.0,23.0,29.0,22.0,30.0,9.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-07,101.0,21.0,30.0,28.0,35.0,16.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-08,106.0,28.0,32.0,28.0,18.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-09,188.0,51.0,71.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-10,221.0,70.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-11,191.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#RFM Segmentation
R:Recency which means when last time each customer ordered
F:Frequency of how many times each customer buy
M:Monetary is total sum ordered by each customer

In [11]:
import sys
from pathlib import Path

root = Path.cwd().parent
sys.path.insert(0, str(root / "src"))

In [12]:
from retail_analytics.features import build_rfm

build_rfm(customers)

,Recency,Frequency,Monetary,M_Score,F_Score,R_Score,RFM,Segment
Customer ID,,,,,,,,
12346,326,12,77556.46,5,5,2,255,At Risk
12347,2,8,5633.32,5,4,5,545,Champions
12348,75,5,1658.40,4,4,3,344,Loyal
12349,19,3,3678.69,5,3,5,535,Loyal
12350,310,1,294.40,2,1,2,212,Lost
...,...,...,...,...,...,...,...,...
18283,4,22,2730.70,4,5,5,554,Champions
18284,432,1,411.68,2,2,1,122,Lost
18285,661,1,377.00,2,2,1,122,Lost
18286,477,2,1246.43,4,3,1,134,At Risk
18287,43,7,4132.99,5,4,4,445,Champions